# Generated by Django 3.1.7 on 2021-03-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visit_time',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
