# Generated by Django 3.1.7 on 2021-03-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
