# Generated by Django 3.1.7 on 2021-03-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210323_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='visit_time',
        ),
    ]
