# Generated by Django 3.1.7 on 2021-03-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210323_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='visit_time',
            field=models.DateField(),
        ),
    ]
