# Generated by Django 3.1.7 on 2021-03-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210323_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='visit_time',
        ),
    ]
