# Generated by Django 3.1.7 on 2021-03-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_visitors_visit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='visit_time',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
