# Generated by Django 3.1.7 on 2021-03-23 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_visitors_visit_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitors',
        ),
    ]
